branch-defaults:
  default:
    environment: AllimsBackendDev-env
environment-defaults:
  AllimsBackendDev-env:
    branch: null
    repository: null
global:
  application_name: allims-backend-dev
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:sa-east-1::platform/Node.js running on
    64bit Amazon Linux/4.11.0
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
